version = 1

test_patterns = [
    "tests/*.py"
]

[[analyzers]]
name = "python"
enabled = true
dependency_file_paths = [
    "pyproject.toml",
    "poetry.lock"
]

[analyzers.meta]
runtime_version = "3.x.x"
max_line_length = 88
type_checker = "mypy"
